const administrator = API.guard('administrator');
let accounts = [];
function notify(message, type = 'success') { document.querySelector('#alert').innerHTML = `<div class="alert alert-${type}">${API.escape(message)}</div>`; }
async function loadAccounts() { document.querySelector('#accounts-table').innerHTML = Array.from({ length: 4 }, () => '<tr class="skeleton-row"><td colspan="6"><span class="skeleton-line"></span></td></tr>').join(''); try { const result = await API.request('/admin/hr-accounts'); accounts = result.accounts; render(); } catch (error) { notify(error.message, 'danger'); } }
function render() {
  const active = accounts.filter((account) => account.user?.is_active).length;
  document.querySelector('#stats').innerHTML = `<div class="col-6 col-lg-3"><div class="panel dashboard-card p-3"><div class="small text-muted-app">HR 總數</div><div class="stat-value">${accounts.length}</div></div></div><div class="col-6 col-lg-3"><div class="panel dashboard-card p-3"><div class="small text-muted-app">啟用帳號</div><div class="stat-value">${active}</div></div></div>`;
  document.querySelector('#accounts-table').innerHTML = accounts.map((account) => `<tr><td><div class="person-cell"><span class="avatar">${API.escape(account.name.slice(0, 1).toUpperCase())}</span><strong>${API.escape(account.name)}</strong></div></td><td><code>${API.escape(account.user?.username)}</code></td><td>${API.escape(account.email || '未提供')}</td><td><span class="badge ${account.user?.is_active ? 'badge-available' : 'badge-cancelled'}">${account.user?.is_active ? '啟用' : '停用'}</span></td><td>${new Date(account.created_at).toLocaleDateString('zh-TW')}</td><td class="text-end action-cell"><button class="btn btn-sm btn-outline-primary me-1" data-edit="${account.id}"><i class="bi bi-pencil me-1"></i>編輯</button><button class="btn btn-sm btn-outline-danger" data-delete="${account.id}"><i class="bi bi-trash me-1"></i>刪除</button></td></tr>`).join('') || '<tr><td colspan="6" class="empty">尚無 HR 帳號。</td></tr>';
}
function openEdit(id) { const account = accounts.find((item) => item.id === id); setForm(account); bootstrap.Modal.getOrCreateInstance(document.querySelector('#account-modal')).show(); }
function setForm(account = null) { document.querySelector('#account-form').reset(); document.querySelector('#account-id').value = account?.id || ''; document.querySelector('#name').value = account?.name || ''; document.querySelector('#username').value = account?.user?.username || ''; document.querySelector('#email').value = account?.email || ''; document.querySelector('#password').required = !account; document.querySelector('#password-hint').textContent = account ? '留空代表不修改' : ''; document.querySelector('#modal-title').textContent = account ? '編輯 HR 帳號' : '新增 HR 帳號'; document.querySelector('#form-alert').innerHTML = ''; }
document.querySelector('#account-modal').addEventListener('show.bs.modal', (event) => { if (event.relatedTarget) setForm(); });
document.querySelector('#account-form').addEventListener('submit', async (event) => { event.preventDefault(); const id = document.querySelector('#account-id').value; const payload = { name: document.querySelector('#name').value, username: document.querySelector('#username').value, email: document.querySelector('#email').value }; if (document.querySelector('#password').value) payload.password = document.querySelector('#password').value; try { await API.request(id ? `/admin/hr-accounts/${id}` : '/admin/hr-accounts', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(payload) }); bootstrap.Modal.getInstance(document.querySelector('#account-modal')).hide(); notify('HR 帳號已儲存。'); loadAccounts(); } catch (error) { document.querySelector('#form-alert').innerHTML = `<div class="alert alert-danger">${API.escape(error.message)}</div>`; } });
document.querySelector('#accounts-table').addEventListener('click', async (event) => { const edit = event.target.closest('[data-edit]'); const remove = event.target.closest('[data-delete]'); if (edit) return openEdit(edit.dataset.edit); if (remove && confirm('確定刪除此 HR 帳號？')) { try { await API.request(`/admin/hr-accounts/${remove.dataset.delete}`, { method: 'DELETE' }); notify('HR 帳號已刪除。'); loadAccounts(); } catch (error) { notify(error.message, 'danger'); } } });
if (administrator) loadAccounts();
