const administrator = API.guard('administrator');
let accounts = [];
function notify(message, type = 'success') { document.querySelector('#alert').innerHTML = `<div class="alert alert-${type}">${API.escape(message)}</div>`; }
function setupFeatureSettings() {
  document.querySelector('#accounts-table').closest('.panel').insertAdjacentHTML('beforebegin', '<section class="panel p-4 mb-4"><div class="d-flex justify-content-between align-items-center gap-3"><div><h2 class="h5 mb-1">HR 功能開關</h2><p class="text-muted-app mb-0">控制 HR 是否可產生主管／面試者的安全空檔填寫連結。</p></div><div class="form-check form-switch"><input class="form-check-input" id="availability-links-enabled" type="checkbox" role="switch"><label class="form-check-label" for="availability-links-enabled">開放填寫連結</label></div></div></section>');
}
function setupAuditLogs() {
  document.querySelector('#accounts-table').closest('.panel').insertAdjacentHTML('afterend', '<section class="panel p-4 mt-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 mb-1">稽核紀錄</h2><p class="text-muted-app mb-0">顯示最近的管理操作；不記錄密碼或安全權杖。</p></div><button class="btn btn-sm btn-outline-secondary" id="refresh-audit-logs">重新整理</button></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>時間</th><th>操作者</th><th>操作</th><th>項目</th><th>內容</th></tr></thead><tbody id="audit-log-table"></tbody></table></div></section>');
}
async function loadAuditLogs() { try { const logs = (await API.request('/admin/audit-logs?limit=100')).logs; document.querySelector('#audit-log-table').innerHTML = logs.map((log) => `<tr><td>${new Date(log.created_at).toLocaleString('zh-TW')}</td><td>${API.escape(log.actor?.username || '系統')}</td><td>${API.escape(log.action)}</td><td>${API.escape(log.entity_type)}${log.entity_id ? `<div class="small text-muted-app">${API.escape(log.entity_id)}</div>` : ''}</td><td><code class="small">${API.escape(JSON.stringify(log.details || {}))}</code></td></tr>`).join('') || '<tr><td colspan="5" class="empty">尚無紀錄。</td></tr>'; } catch (error) { notify(error.message, 'danger'); } }
async function loadFeatureSettings() {
  try { const settings = await API.request('/admin/settings/features'); document.querySelector('#availability-links-enabled').checked = settings.availabilityLinksEnabled; }
  catch (error) { notify(error.message, 'danger'); }
}
async function loadAccounts() { document.querySelector('#accounts-table').innerHTML = Array.from({ length: 4 }, () => '<tr class="skeleton-row"><td colspan="6"><span class="skeleton-line"></span></td></tr>').join(''); try { const result = await API.request('/admin/hr-accounts'); accounts = result.accounts; render(); } catch (error) { notify(error.message, 'danger'); } }
function render() {
  const active = accounts.filter((account) => account.user?.is_active).length;
  document.querySelector('#stats').innerHTML = `<div class="col-6 col-lg-3"><div class="panel dashboard-card p-3"><div class="small text-muted-app">HR 總數</div><div class="stat-value">${accounts.length}</div></div></div><div class="col-6 col-lg-3"><div class="panel dashboard-card p-3"><div class="small text-muted-app">啟用帳號</div><div class="stat-value">${active}</div></div></div>`;
  document.querySelector('#accounts-table').innerHTML = accounts.map((account) => `<tr><td><div class="person-cell"><span class="avatar">${API.escape(account.name.slice(0, 1).toUpperCase())}</span><strong>${API.escape(account.name)}</strong></div></td><td><code>${API.escape(account.user?.username)}</code></td><td>${API.escape(account.email || '未提供')}</td><td><span class="badge ${account.user?.is_active ? 'badge-available' : 'badge-cancelled'}">${account.user?.is_active ? '啟用' : '停用'}</span></td><td>${new Date(account.created_at).toLocaleDateString('zh-TW')}</td><td class="text-end action-cell"><button class="btn btn-sm btn-outline-primary me-1" data-edit="${account.id}"><i class="bi bi-pencil me-1"></i>編輯</button><button class="btn btn-sm btn-outline-danger" data-delete="${account.id}"><i class="bi bi-trash me-1"></i>刪除</button></td></tr>`).join('') || '<tr><td colspan="6" class="empty">尚無 HR 帳號。</td></tr>';
}
function openEdit(id) { const account = accounts.find((item) => item.id === id); setForm(account); bootstrap.Modal.getOrCreateInstance(document.querySelector('#account-modal')).show(); }
function setForm(account = null) { document.querySelector('#account-form').reset(); document.querySelector('#account-id').value = account?.id || ''; document.querySelector('#name').value = account?.name || ''; document.querySelector('#username').value = account?.user?.username || ''; document.querySelector('#email').value = account?.email || ''; document.querySelector('#password').required = !account; document.querySelector('#password-hint').textContent = account ? '留空代表不修改' : ''; document.querySelector('#modal-title').textContent = account ? '編輯 HR 帳號' : '新增 HR 帳號'; document.querySelector('#form-alert').innerHTML = ''; }
document.querySelector('#account-modal').addEventListener('show.bs.modal', (event) => { if (event.relatedTarget) setForm(); });
document.querySelector('#account-form').addEventListener('submit', async (event) => { event.preventDefault(); const id = document.querySelector('#account-id').value; const payload = { name: document.querySelector('#name').value, username: document.querySelector('#username').value, email: document.querySelector('#email').value }; if (document.querySelector('#password').value) payload.password = document.querySelector('#password').value; try { await API.request(id ? `/admin/hr-accounts/${id}` : '/admin/hr-accounts', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(payload) }); bootstrap.Modal.getInstance(document.querySelector('#account-modal')).hide(); notify('HR 帳號已儲存。'); loadAccounts(); } catch (error) { document.querySelector('#form-alert').innerHTML = `<div class="alert alert-danger">${API.escape(error.message)}</div>`; } });
document.querySelector('#accounts-table').addEventListener('click', async (event) => { const edit = event.target.closest('[data-edit]'); const remove = event.target.closest('[data-delete]'); if (edit) return openEdit(edit.dataset.edit); if (remove && confirm('確定刪除此 HR 帳號？')) { try { await API.request(`/admin/hr-accounts/${remove.dataset.delete}`, { method: 'DELETE' }); notify('HR 帳號已刪除。'); loadAccounts(); } catch (error) { notify(error.message, 'danger'); } } });
document.addEventListener('change', async (event) => {
  if (!event.target.matches('#availability-links-enabled')) return;
  event.target.disabled = true;
  try { await API.request('/admin/settings/features', { method: 'PATCH', body: JSON.stringify({ availabilityLinksEnabled: event.target.checked }) }); notify(`安全空檔填寫連結已${event.target.checked ? '開啟' : '關閉'}。`); }
  catch (error) { event.target.checked = !event.target.checked; notify(error.message, 'danger'); }
  finally { event.target.disabled = false; }
});
if (administrator) { setupFeatureSettings(); setupAuditLogs(); loadFeatureSettings(); loadAccounts(); loadAuditLogs(); document.querySelector('#refresh-audit-logs').addEventListener('click', loadAuditLogs); }
